#!/usr/bin/env node
/**
 * Combines multiple Prisma schema files from prisma/schema/ directory
 * into a single prisma/combined-schema.prisma file for Docker builds.
 *
 * This is needed because Prisma's multi-file schema support via prisma.config.ts
 * doesn't work reliably in Docker environments.
 */

const fs = require('fs');
const path = require('path');

const SCHEMA_DIR = path.join(__dirname, '..', 'prisma', 'schema');
const OUTPUT_FILE = path.join(__dirname, '..', 'prisma', 'combined-schema.prisma');

console.log('Combining Prisma schemas...');
console.log(`  Source: ${SCHEMA_DIR}`);
console.log(`  Output: ${OUTPUT_FILE}`);

// Read all .prisma files from schema directory
const schemaFiles = fs.readdirSync(SCHEMA_DIR)
  .filter(file => file.endsWith('.prisma'))
  .sort(); // Ensure consistent ordering

if (schemaFiles.length === 0) {
  console.error('Error: No .prisma files found in schema directory');
  process.exit(1);
}

console.log(`  Found ${schemaFiles.length} schema files:`, schemaFiles.join(', '));

// Combine schemas
const combinedContent = [
  '// ============================================================================',
  '// GENERATED FILE - DO NOT EDIT MANUALLY',
  '// This file is automatically generated by scripts/combine-schemas.js',
  '// Source files are in prisma/schema/',
  '// ============================================================================',
  '',
  ...schemaFiles.map(file => {
    const filePath = path.join(SCHEMA_DIR, file);
    const content = fs.readFileSync(filePath, 'utf8');
    return [
      `// ============================================================================`,
      `// From: ${file}`,
      `// ============================================================================`,
      '',
      content.trim(),
      ''
    ].join('\n');
  })
].join('\n');

// Write combined schema
fs.writeFileSync(OUTPUT_FILE, combinedContent, 'utf8');

console.log(`✓ Combined schema written to: ${OUTPUT_FILE}`);
console.log(`  Total size: ${combinedContent.length} bytes`);
